package okonkwo;

import java.util.NoSuchElementException;

/**
 * A dictionary class that extends the {@code BSTree} class. It is a binary search tree that stores words in alphabetical order and case-insensitively.
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * 
 * @author Taj Okonkwo
 * @version 1.0
 */
public class Dictionary extends BSTree<String> {

	/**
	 * Default Constructor | Create empty dictionary
	 */
	public Dictionary() {
		super();
	}
	
	/**
	 * Unsupported operation | Use {@code insertWordNode()} instead.
	 * @throws UnsupportedOperationException
	 */
	@Override
	public void add(String word) {
		throw new UnsupportedOperationException("Use 'insertWordNode' instead");
	}
	
	/**
	 * Unsupported operation | Use {@code checkWord()} instead.
	 * @throws UnsupportedOperationException
	 */
	@Override
	public void remove(String word) {
		throw new UnsupportedOperationException("Use 'checkWord' instead");
	}
	
	/**
	 * Unsupported operation | Use {@code spellCheck()} instead.
	 * @throws UnsupportedOperationException
	 */
	@Override
	public boolean contains(String word) {
		throw new UnsupportedOperationException("Use 'spellCheck' instead");
	}
	
	/**
	 * Add a word node to the dictionary (case-insensitive)
	 * <p>The word can only contain letter characters with no spaces; automatically lowercase</p>
	 * @param word - The word string to add
	 * @throws DuplicateNodeException if {@code word} already exists in
	 *                                the dictionary
	 * @throws IllegalArgumentException if {@code word} contains non-letter characters or is empty
	 */
	public void insertWordNode(String word) {
		// 1. Check for non-letter characters
		for (char c: word.toCharArray()) {
			if (!Character.isAlphabetic(c))
				throw new IllegalArgumentException("The word '" + word + "' contains non-letter characters.");
		}
		
		// 2. Check if empty string
		if (word.isEmpty())
			throw new IllegalArgumentException("The word cannot be empty.");
		
		// 2. Add the word
		super.add(word.toLowerCase());
	}
	
	/**
	 * Remove a word node from the dictionary (case-insensitive)
	 * @param word - The word string to remove
	 * @throws EmptyTreeException     if attempting to remove an element from an
	 *                                empty dictionary
	 * @throws NoSuchElementException if {@code word} does not exist in the dictionary
	 *
	 */
	public void checkWord(String word) {
		super.remove(word.toLowerCase());
	}
	
	/**
	 * Returns whether a word is contained in the dictionary (case-insensitive)
	 * @param word - The word to search for
	 * @return if the word exists
	 */
	public boolean spellCheck(String word) {
		return super.contains(word.toLowerCase());
	}
	
}
