package okonkwo;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JEditorPane;
import javax.swing.JButton;
import javax.swing.JTextPane;

import okonkwo.BSTree.DuplicateNodeException;

import javax.swing.JScrollPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * A GUI application that allows the user to input a message and check for misspelled words against a dictionary.
 * The dictionary is populated using runtime arguments passed to the application. The user can input a message in the text area and click the "Spell Check" button to check for misspelled words. The misspelled words are displayed in the output text area.
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * 
 * @author Taj Okonkwo
 * @version 1.0
 */
public class Main {

	private JFrame frame;
	JEditorPane editorIn = new JEditorPane();
	JTextPane txtOut = new JTextPane();
	JTextPane txtDictionary = new JTextPane();
	public static Dictionary dict = new Dictionary();
	
	private static String[] words;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		words = args;
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Main window = new Main();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public Main() {
		initialize();
		
		// Open dictionary
		// 1. Fill dict with words from args
		for (String word: words) {
			String alphaWord = word.replaceAll("[^a-zA-Z]", "");
			
			try {
				dict.insertWordNode(alphaWord);
			} catch (DuplicateNodeException dupNode) {
				
			} catch (IllegalArgumentException illArg) {
				
			}
		}
		
		// 2. Show dictionary in GUI
		txtDictionary.setText("Dictionary:\n\n" + dict.toString());
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 450, 300);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);
		
		JLabel lblTitle = new JLabel("Dictionary App");
		lblTitle.setToolTipText("Type message here");
		lblTitle.setFont(new Font("Tahoma", Font.PLAIN, 19));
		lblTitle.setBounds(152, 11, 127, 19);
		frame.getContentPane().add(lblTitle);
		
		editorIn.setToolTipText("");
		editorIn.setBounds(10, 65, 213, 187);
		frame.getContentPane().add(editorIn);
		
		JLabel lblMessage = new JLabel("Message");
		lblMessage.setBounds(10, 46, 119, 14);
		frame.getContentPane().add(lblMessage);
		
		JButton btnRun = new JButton("Spell Check");
		btnRun.addMouseListener(new MouseAdapter() {
			@Override
			/**
			 * When the button is clicked, spell check the message and display the output
			 */
			public void mouseClicked(MouseEvent e) {
				// 1. Get the message from the editor
				String message = editorIn.getText();
				
				// 2. Convert the message to a list of words
				String[] messageWords = message.split("\\W+");
				
				// 3. Check each word in the message against the dictionary
				ArrayList<String> misspelledWords = new ArrayList<>();
				for (String word: messageWords) {
					if (!dict.spellCheck(word)) {
						misspelledWords.add(word);
					}
				}
				
				// 4. Display the misspelled words in the output text pane
				if (misspelledWords.isEmpty()) {
					txtOut.setText("No misspelled words found.");
				} else {
					txtOut.setText("Misspelled words: " + String.join(", ", misspelledWords));
				}
			}
		});
		btnRun.setBounds(113, 42, 110, 22);
		frame.getContentPane().add(btnRun);
		
		JScrollPane scrollDict = new JScrollPane();
		scrollDict.setBounds(233, 62, 193, 89);
		frame.getContentPane().add(scrollDict);
		
		txtDictionary.setEditable(false);
		scrollDict.setViewportView(txtDictionary);
		
		JScrollPane scrollOut = new JScrollPane();
		scrollOut.setBounds(233, 163, 193, 89);
		frame.getContentPane().add(scrollOut);
		
		txtOut.setEditable(false);
		scrollOut.setViewportView(txtOut);
	}
}
