package okonkwo;

/**
 * Dollars class | Represents a dollar amount
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 */
public class Dollars {
	
	// Data Members
	private float dollars;

	/**
	 * Create new dollar amount
	 * @param dollars
	 */
	public Dollars(float dollars) {
		super();
		this.dollars = round(dollars, 2);
	}

	/**
	 * Hash code of dollar amount
	 */
	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return Float.hashCode(dollars);
	}

	/**
	 * Are two dollar values equal?
	 */
	@Override
	public boolean equals(Object obj) {
		// TODO Auto-generated method stub
		if (!(obj instanceof Dollars))
			return false;
		return ((Dollars) obj).getDollars() == dollars;
	}

	/**
	 * A clone of the dollar amount
	 */
	@Override
	protected Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}
	
	/**
	 * The string representation of the dollar amount
	 */
	@Override
	public String toString() {
		// Add zeroes to the end of price up to hundredths place
		String dolStr = dollars + "";
		int places = dolStr.substring(dolStr.indexOf('.')).length();
		while (places <= 2) {
			dolStr += "0";
			places++;
		}
		return "$" + dolStr;
	}

	/**
	 * Get the dollar amount (rounded 2 decimals)
	 * @return
	 */
	public float getDollars() {
		return dollars;
	}

	/**
	 * Set the dollar amount (rounded 2 decimals)
	 * @param dollars
	 */
	public void setDollars(float dollars) {
		this.dollars = round(dollars, 2);
	}
	
	/**
	 * Round a float to a certain number of decimal places
	 * @param f - the float to be rounded
	 * @param decimals - the number of decimal places
	 * @return rounded float
	 */
	public static float round(float f, int decimals) {
		// 1. Create another float with value = f * 10^decimals
		float roundedF = (float) (f * Math.pow(10, decimals));
		
		// 2. Round the new float
		roundedF = Math.round(roundedF);
		
		// 3. Divide the float by 10^decimals
		roundedF /= Math.pow(10, decimals);
		
		// 4. Return float
		return roundedF;
	}

}
