package okonkwo;

import java.util.ArrayList;

/**
 * SalesSlip class | Represents a sales slip with a list of {@code SalesItem}s
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 */
public class SalesSlip {
	
	// Data Members
	/**The items on the slip */
	private ArrayList<SalesItem> items;
	
	// Constructors
	/**
	 * Default constructor | Creates an empty {@code SalesSlip}
	 */
	public SalesSlip() {
		items = new ArrayList<>();
	}
	
	// New Methods
	/**
	 * Add a new {@code SalesItem} to the slip
	 * @param salesItem
	 */
	public void addItem(SalesItem salesItem) {
		items.add(salesItem);
	}
	
	/**
	 * The total of all item prices
	 * @return total
	 */
	public Dollars totalSales() {
		// 1. Track current sales (0)
		float sales = 0;
		
		// 2. Go through each item and add to sales its price value times its quantity
		for (SalesItem s: items)
			sales += s.getPrice().getDollars() * s.getQuantity();
		
		// 3. Return sales
		return new Dollars(sales);
	}
	
	// Basic Methods
	/**
	 * The {@code SalesSlip} as a string
	 */
	@Override
	public String toString() {
		// 1. Start with an empty string
		String str = "";
		
		// 2. Go through each item and add it to the string followed by a new line if not the last element
		for (int i = 0; i < items.size(); i++) {
			str += items.get(i);
			if (i != items.size() - 1)
				str += "\n";
		}
		
		// 3. Return the string
		return str;
	}

}
