package okonkwo;

/**
 * SalesItem class | Represents a sales item with a name, price, and quantity
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 */
public class SalesItem {
	
	// Data Members
	/**The item name */
	private String name;
	
	/**The price per item ($) (rounded to 2 decimals)*/
	private Dollars price; // Float used instead of double because precision is not as relevant
	
	/**The item quantity */
	private int quantity;
	
	// Constructors
	/**
	 * Explicit constructor | Create a {@code SalesItem} with a name, price, and quantity
	 * @param name
	 * @param price ({@code float}) (rounded to 2 decimals)
	 * @param quantity
	 */
	public SalesItem(String name, Dollars price, int quantity) {
		super();
		this.name = name;
		this.price = price;
		this.quantity = quantity;
	}
	
	/**
	 * Explicit constructor | Create a {@code SalesItem} with a name, price, and quantity
	 * @param name
	 * @param price ({@code Dollars}) (rounded to 2 decimals)
	 * @param quantity
	 */
	public SalesItem(String name, float price, int quantity) {
		super();
		this.name = name;
		this.price = new Dollars(price);
		this.quantity = quantity;
	}
	
	// Basic Methods
	/**
	 * The {@code SalesItem} as a string
	 */
	@Override
	public String toString() {
		return name + " \t" + price + " \t" + quantity;
	}

	/**
	 * Get item name
	 * @return item name
	 */
	public String getName() {
		return name;
	}

	/**
	 * Set item name
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get price per item in dollars
	 * @return price per item in dollars
	 */
	public Dollars getPrice() {
		return price;
	}

	/**
	 * Set price per item in dollars (rounded to 2 decimals)
	 * @param price
	 */
	public void setPrice(Dollars price) {
		this.price = price;
	}

	/**
	 * Get item quantity
	 * @return item quantity
	 */
	public int getQuantity() {
		return quantity;
	}

	/**
	 * Set item quantity
	 * @param quantity
	 */
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
