package okonkwo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Set;

/**
 * A class that represents a tile with a letter on it.
 * <p>Comments and parts of code generated by GitHub Copilot</p>
 * 
 * @author Taj Okonkwo
 * @version 1.0
 */
public class Tile {

	// Data Members
	/**
	 * The letter on the tile.
	 */
	private char letter;

	// Constructors
	/**
	 * Constructs a tile with the given letter. The letter will be upper-case
	 * 
	 * @param letter the letter on the tile
	 */
	public Tile(char letter) {
		super();

		if (!(('a' <= letter && letter <= 'z') || ('A' <= letter && letter <= 'Z')))
			throw new NotALetterException("'" + letter + "' was entered. Only letters allowed!");

		this.letter = Character.toUpperCase(letter);
	}

	// Exceptions
	/**
	 * An exception that is thrown when a non-letter character is used to create a
	 * Tile.
	 */
	public static class NotALetterException extends RuntimeException {

		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;

		public NotALetterException() {
			super();
			// TODO Auto-generated constructor stub
		}

		public NotALetterException(String message, Throwable cause, boolean enableSuppression,
				boolean writableStackTrace) {
			super(message, cause, enableSuppression, writableStackTrace);
			// TODO Auto-generated constructor stub
		}

		public NotALetterException(String message, Throwable cause) {
			super(message, cause);
			// TODO Auto-generated constructor stub
		}

		public NotALetterException(String message) {
			super(message);
			// TODO Auto-generated constructor stub
		}

		public NotALetterException(Throwable cause) {
			super(cause);
			// TODO Auto-generated constructor stub
		}

	}

	// Methods
	/**
	 * Returns the letter on the tile.
	 * 
	 * @return the letter on the tile
	 */
	public char getLetter() {
		return letter;
	}

	@Override
	public boolean equals(Object o2) {
		if (this == o2)
			return true;
		if (o2 == null)
			return false;
		if (getClass() != o2.getClass())
			return false;
		Tile other = (Tile) o2;
		return this.letter == other.letter;
	}

	@Override
	public String toString() {
		return "" + letter;
	}

	/**
	 * Overrides {@code Object.hashCode()} by only checking letter equivalence
	 */
	@Override
	public int hashCode() {
		// Must be consistent with equals so HashSet and other hash-based
		// collections can correctly detect Tiles with the same letter.
		return Character.hashCode(letter);
	}

	/**
	 * Returns a {@code HashSet} of unique permutations of the given list of tiles.
	 * 
	 * @param tileList an {@code ArrayList} of {@code Tile} objects
	 * @return a {@code HashSet} of unique permutations of the list
	 */
	public static HashSet<ArrayList<Tile>> uniquePermutations(ArrayList<Tile> tileList) {
		// 1. Create a HashSet to store unique permutations
		HashSet<ArrayList<Tile>> uniquePerms = new HashSet<>();
		
		// 2. Count the number of unique tiles in the list as a map
		HashMap<Tile, Integer> tileCountMap = new HashMap<>();
		for (Tile tile : tileList) {
		    tileCountMap.put(tile, tileCountMap.getOrDefault(tile, 0) + 1);
		}
		
		// 3. Create a sorted list of unique tiles from the input list
		ArrayList<Tile> uniqueTiles = new ArrayList<>(tileCountMap.keySet());
		uniqueTiles.sort((t1, t2) -> Character.compare(t1.getLetter(), t2.getLetter()));
		
		// 4. Create a list to store the current permutation
		ArrayList<Tile> currentPerm = new ArrayList<>();
		
		// 5. Call the recursive helper function to generate permutations
		generatePermutations(uniqueTiles, tileCountMap, currentPerm, tileList.size(), uniquePerms);
		
		// 6. Return the HashSet of unique permutations
		return uniquePerms;
	}
	
	/**
	 * A recursive helper function to generate unique permutations of tiles.
	 * 
	 * @param uniqueTiles a sorted list of unique {@code Tile} objects
	 * @param tileCountMap a map of {@code Tile} objects to their counts in the input list
	 * @param currentPerm the current permutation being built
	 * @param totalLength the total length of the input list
	 * @param uniquePerms a {@code HashSet} to store unique permutations
	 */
	private static void generatePermutations(ArrayList<Tile> uniqueTiles, HashMap<Tile, Integer> tileCountMap,
	        ArrayList<Tile> currentPerm, int totalLength, HashSet<ArrayList<Tile>> uniquePerms) {
		// 1. Base case: if the current permutation has reached the total length, add it to the unique permutations set
	    if (currentPerm.size() == totalLength) {
	        uniquePerms.add(new ArrayList<>(currentPerm));
	        return;
	    }
	    
	    // 2. Iterate through the unique tiles and generate permutations recursively
	    for (Tile tile : uniqueTiles) {
	        int count = tileCountMap.get(tile);
	        if (count > 0) {
	        	// 3. Add the tile to the current permutation and decrement its count in the map
	            currentPerm.add(tile);
	            tileCountMap.put(tile, count - 1);
	            
	            // 4. Recursively generate permutations with the updated current permutation and tile count map
	            generatePermutations(uniqueTiles, tileCountMap, currentPerm, totalLength, uniquePerms);
	            
	            // 5. Backtrack: remove the last tile from the current permutation and restore its count in the map
	            currentPerm.remove(currentPerm.size() - 1);
	            tileCountMap.put(tile, count);
	        }
	    }
	}

	/**
	 * Returns the number of unique elements in the given list of tiles.
	 * 
	 * @param tileList an {@code ArrayList} of {@code Tile} objects
	 * @return the number of unique elements in the list
	 */
	public static int numUniqueTiles(ArrayList<Tile> tileList) {
		HashSet<Tile> uniqueElements = new HashSet<Tile>(tileList);
		return uniqueElements.size();
	}
}