package tester;

import okonkwo.PasswordApp;

/**
 * TesterPasswords class is used to test the longestBlock method from the PasswordApp class.
 * It contains various test cases to validate the correctness of the method.
 * 
 * <p>Comments and parts of code generated by GitHub Copilot</p>
 * 
 * @author Taj Okonkwo
 * @version 1.0
 */
public class TesterPasswords {

	public static void main(String[] args) {
		// Test longestBlock method
		// 1. Create various test cases for the longestBlock method
		System.out.println("Testing longestBlock() method:");
		String[] testCases = {
				"aaabbcc", // longest block is 3
				"abcd", // longest block is 1
				"aaabbbbccc", // longest block is 4
				"abcdeeeeeee", // longest block is 7
				"", // longest block is 0
				"a", // longest block is 1
				"aaabbbcccddd", // longest block is 3
				"ababababab", // longest block is 1
		};
		
		// 2. Test the longestBlock method with the test cases
		for (String testCase : testCases) {
			int result = PasswordApp.longestBlock(testCase);
			System.out.println("Input: " + testCase + " | Longest Block: " + result);
		}
		
		// Test evaluate method
		// 1. Create various test cases for the evaluate method
		String[] evaluateTestCases = {
				"aaabbcc", // Weak
				"abcd", // Weak
				"aaabbbbccc", // Strong
				"abcdeeeeeee", // Strong
				"", // Weak
				"a", // Weak
				"aaabbbcccccccccccccddd", // Strong
				"ababababab", // Weak
		};
		
		// 2. Test the evaluate method with the test cases
		System.out.println("\nTesting evaluate() method:");
		for (String testCase : evaluateTestCases) {
			String result = PasswordApp.evaluate(testCase);
			System.out.println("Input: " + testCase + " | Evaluation: " + result);
		}
	}
	
}
