package tester;

import java.util.ArrayList;
import java.util.HashSet;

import okonkwo.Tile;

/**
 * A test main class
 * <p>Comments and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 */
public class TesterMain {

	/**
	 * The main method that tests the Tile class
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		// Test Tile class
		ArrayList<Tile> myTileList = new ArrayList<>();
		
		// Test if two tiles are the same
		
		myTileList.add(new Tile('A'));
		myTileList.add(new Tile('B'));
		myTileList.add(new Tile('C'));
		myTileList.add(new Tile('D'));
		myTileList.add(new Tile('E'));
		int size = myTileList.size();
		
		HashSet<ArrayList<Tile>> perms = Tile.uniquePermutations(myTileList);
		System.out.println("Permutations: " + perms);
		System.out.println("Size of list: " + size);
		System.out.println("Size of perms: " + perms.size());
	}

}
