package okonkwo;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.InterruptedIOException;
import java.util.Scanner;

import javax.swing.JFileChooser;

/**
 * A class for reading files using {@code JFileChooser}
 * <p>Assistance: https://docs.oracle.com/javase/tutorial/uiswing/components/filechooser.html</p>
 * 
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 */
public class FileHandler {
	
	// Data Members
	private File file;
	private Scanner scanner;
	private JFileChooser chooser;
	
	// Constructors
	/**
	 * Explicit constructor | Create a file handler with a chooser
	 * @param chooser
	 */
	public FileHandler(JFileChooser chooser) {
		this.chooser = chooser;
	}
	
	// Methods
	/**
	 * Open a file from the {@code JFileChooser} GUI menu
	 * @throws InterruptedIOException if the dialog is exited
	 */
	public void chooseFile() throws InterruptedIOException {
		// 1. Open the file chooser
		int open = chooser.showOpenDialog(null);
		
		// 2. Get file path from chooser
		if (open == JFileChooser.APPROVE_OPTION) {
			file = chooser.getSelectedFile();
		} else {
			// Cancelled
			throw new InterruptedIOException("Dialog closed");
		}
	}
	
	public String fileText() throws FileNotFoundException {
		// 1. Read the file
		scanner = new Scanner(file);
		
		// 2. Build the text string with new lines separating lines
		String text = "";
		while (scanner.hasNextLine()) {
			text += scanner.nextLine() + "\n";
		}
		
		// 3. Return text
		return text.substring(0, text.length() - 1); // Removes last line break
	}
	
	public DoubleList toDoubleList() throws FileNotFoundException {
		// 1. Take the file's text
		String text = fileText();
		
		// 2. Split it by line breaks
		String[] split = text.split("\n");
		
		// 3. Parse each element as a double and add to the return list
		DoubleList list = new DoubleList();
		for (String elem: split) {
			list.add(Double.parseDouble(elem));
		}
		
		// 4. Return the list
		return list;
	}
	
	// Getters & Setters
	/**
	 * Return the most recently selected file
	 * @return the file
	 */
	public File getFile() {
		return file;
	}

}
