package okonkwo;

/**
 * A class for calculating statistics
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 */
public class StatCalculator {

	// Methods
	/**
	 * Find the mean of a list of doubles
	 * @param list - the list of doubles
	 * @return the mean
	 */
	public static double mean(DoubleList list) {
		// 1. Sum the values
		double sum = 0;
		for (Double d: list)
			sum += d;
		
		// 2. Return the sum divided by size
		return sum / list.size();
	}
	
	/**
	 * Find the standard deviation of a list of doubles
	 * <p>Formula from https://www.mathsisfun.com/data/standard-deviation-formulas.html</p>
	 * @param list - the list of doubles
	 * @return the standard deviation
	 */
	public static double stDev(DoubleList list) {
		// 1. Calculate the mean
		double mean = mean(list);
		
		// 2. Perform the sum part of the stdev formula
		double stDevSum = 0;
		for (Double d: list) {
			stDevSum = Math.pow(d - mean, 2);
		}
		
		// 3. Plug values into formula
		return Math.sqrt((1 / (double)list.size()) * stDevSum);
	}
	
}
