package tester;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import java.util.Arrays;
import java.util.Iterator;

import org.junit.jupiter.api.Test;

import okonkwo.LinkedList;

/**
 * Test class for the {@code LinkedList} class
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 *
 */
class TestLinkedList {

	/**
	 * Test the constructor
	 */
	@Test
	void testLinkedList() {
		// 1. Create linked list
		LinkedList<Integer> list = new LinkedList<>();
		
		// 2. Assert that the list is empty
		assertTrue(list.isEmpty());
	}

	/**
	 * Test the {@code size()} method
	 */
	@Test
	void testSize() {
		// 1. Create lists of various sizes
		LinkedList<Integer> list0 = new LinkedList<>();
		LinkedList<Integer> list1 = new LinkedList<>();
		LinkedList<Integer> list2 = new LinkedList<>();
		LinkedList<Integer> list3 = new LinkedList<>();
		LinkedList<Integer> list4 = new LinkedList<>();
		LinkedList<Integer> list5 = new LinkedList<>();
		
		// 2. Add elements to the lists
		for (int i = 0; i < 1; i++) {
			list1.add(i);
		}
		for (int i = 0; i < 2; i++) {
			list2.add(i);
		}
		for (int i = 0; i < 3; i++) {
			list3.add(i);
		}
		for (int i = 0; i < 4; i++) {
			list4.add(i);
		}
		for (int i = 0; i < 5; i++) {
			list5.add(i);
		}
		
		// 3. Assert that the sizes are correct
		assertEquals(0, list0.size());
		assertEquals(1, list1.size());
		assertEquals(2, list2.size());
		assertEquals(3, list3.size());
		assertEquals(4, list4.size());
		assertEquals(5, list5.size());
	}

	/**
	 * Test the {@code isEmpty()} method
	 */
	@Test
	void testIsEmpty() {
		// 1. Create an empty list
		LinkedList<Integer> emptyList = new LinkedList<>();
		
		// 2. Create a non-empty list
		LinkedList<Integer> nonEmptyList = new LinkedList<>();
		nonEmptyList.add(1);
		
		// 3. Assert that the empty list is empty and the non-empty list is not empty
		assertTrue(emptyList.isEmpty());
		assertFalse(nonEmptyList.isEmpty());
	}

	/**
	 * Test the {@code contains()} method
	 */
	@Test
	void testContains() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		list.add(1);
		list.add(2);
		
		// 2. Assert that the list contains the added elements
		assertTrue(list.contains(1));
		assertTrue(list.contains(2));
		assertFalse(list.contains(3)); // Element not in the list
	}

	@Test
	void testIterator() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Use the iterator to traverse the list and collect elements
		Iterator<Integer> iterator = list.iterator();
		int index = 0;
		while (iterator.hasNext()) {
			Integer value = iterator.next();
			assertEquals(index, value); // Check that the value matches the expected index
			index++;
		}
		
		// 3. Create an empty list and assert that the iterator has no elements
		LinkedList<Integer> emptyList = new LinkedList<>();
		Iterator<Integer> emptyIterator = emptyList.iterator();
		assertFalse(emptyIterator.hasNext());
	}

	/**
	 * Test the {@code toArray()} method
	 */
	@Test
	void testToArray() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Convert the list to an array
		Object[] array = list.toArray();
		
		// 3. Assert that the array has the correct size and elements
		assertEquals(5, array.length);
		for (int i = 0; i < 5; i++) {
			assertEquals(i, array[i]);
		}
	}

	/**
	 * Test the {@code toArray(T[] a)} method
	 */
	@Test
	void testToArrayTArray() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.toArray(new Integer[0]);
		});
	}

	/**
	 * Test the {@code add(E e)} method
	 */
	@Test
	void testAddE() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Assert that the list contains the added elements
		for (int i = 0; i < 5; i++) {
			assertTrue(list.contains(i));
		}
	}

	@Test
	void testRemoveObject() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 10; i++) {
			list.add(i);
		}
		int initialSize = list.size();
		
		// 2. Remove an element and assert that it is no longer in the list
		assertTrue(list.remove(Integer.valueOf(5)));
		
		// 3. Assert that removing an element not in the list returns false
		assertFalse(list.remove(Integer.valueOf(10)));
		
		// 4. Assert that the list no longer contains the removed element
		assertFalse(list.contains(5));
		
		// 5. Assert that the size of the list has decreased by 1
		assertEquals(initialSize - 1, list.size());
		
		// 6. Remove the first and last elements and check the size again
		assertTrue(list.remove(Integer.valueOf(0)));
		assertEquals(initialSize - 2, list.size());
		
		assertTrue(list.remove(Integer.valueOf(4)));
		assertEquals(initialSize - 3, list.size());
	}

	/**
	 * Test the {@code containsAll(Collection<?> c)} method
	 */
	@Test
	void testContainsAll() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Create a collection that is a subset of the list
		List<Integer> subset = Arrays.asList(1, 2, 3);
		
		// 3. Assert that the list contains all elements of the subset
		assertTrue(list.containsAll(subset));
		
		// 4. Create a collection that has an element not in the list
		List<Integer> notSubset = Arrays.asList(1, 2, 6);
		
		// 5. Assert that the list does not contain all elements of this collection
		assertFalse(list.containsAll(notSubset));
	}

	/**
	 * Test the {@code addAll(Collection<? extends E> c)} method
	 */
	@Test
	void testAddAllCollectionOfQextendsE() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Create a collection to add to the list
		java.util.List<Integer> toAdd = java.util.Arrays.asList(5, 6, 7);
		
		// 3. Add all elements of the collection to the list
		assertTrue(list.addAll(toAdd));
		
		// 4. Assert that the list now contains all elements of the collection
		for (Integer elem : toAdd) {
			assertTrue(list.contains(elem));
		}
		
		// 5. Assert that the size of the list has increased by the size of the collection
		assertEquals(8, list.size());
	}

	/**
	 * Test the {@code removeAll(Collection<?> c)} method
	 */
	@Test
	void testAddAllIntCollectionOfQextendsE() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.addAll(0, java.util.Arrays.asList(1, 2, 3));
		});
	}

	/**
	 * Test the {@code removeAll(Collection<?> c)} method
	 */
	@Test
	void testRemoveAll() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 10; i++) {
			list.add(i);
		}
		
		// 2. Create a collection of elements to remove
		List<Integer> toRemove = Arrays.asList(2, 4, 6, 8);
		
		// 3. Remove all elements of the collection from the list
		assertTrue(list.removeAll(toRemove));
		
		// 4. Assert that the list no longer contains the removed elements
		for (Integer elem : toRemove) {
			assertFalse(list.contains(elem));
		}
		
		// 5. Assert that the size of the list has decreased by the size of the collection
		assertEquals(6, list.size());
		
		// 6. Attempt to remove elements not in the list and assert that it returns false
		List<Integer> notInList = Arrays.asList(10, 11);
		assertFalse(list.removeAll(notInList));
	}

	/**
	 * Test the {@code retainAll(Collection<?> c)} method
	 */
	@Test
	void testRetainAll() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.retainAll(java.util.Arrays.asList(1, 2, 3));
		});
	}

	/**
	 * Test the {@code clear()} method
	 */
	@Test
	void testClear() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Clear the list
		list.clear();
		
		// 3. Assert that the list is empty and size is 0
		assertTrue(list.isEmpty());
	}

	/**
	 * Test the {@code get(int index)} method
	 */
	@Test
	void testGet() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Assert that getting elements by index returns the correct values
		for (int i = 0; i < 5; i++) {
			assertEquals(i, list.get(i));
		}
	}

	/**
	 * Test the {@code set(int index, E element)} method
	 */
	@Test
	void testSet() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Set new values at each index and assert that the old values are returned
		for (int i = 0; i < 5; i++) {
			int oldValue = list.set(i, i + 10);
			assertEquals(i, oldValue); // Old value should be the original
			assertEquals(i + 10, list.get(i)); // New value should be set correctly
		}
	}

	/**
	 * Test the {@code add(int index, E element)} method
	 */
	@Test
	void testAddIntE() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.add(0, 1);
		});
	}

	/**
	 * Test the {@code remove(int index)} method
	 */
	@Test
	void testRemoveInt() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.remove(0);
		});
	}

	/**
	 * Test the {@code indexOf(Object o)} method
	 */
	@Test
	void testIndexOf() {
		// 1. Create a list and add some elements
		LinkedList<Integer> list = new LinkedList<>();
		for (int i = 0; i < 5; i++) {
			list.add(i);
		}
		
		// 2. Assert that the indexOf method returns the correct indices
		for (int i = 0; i < 5; i++) {
			assertEquals(i, list.indexOf(i));
		}
	}

	/**
	 * Test the {@code lastIndexOf(Object o)} method
	 */
	@Test
	void testLastIndexOf() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.lastIndexOf(1);
		});
	}

	/**
	 * Test the {@code listIterator()} method
	 */
	@Test
	void testListIterator() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.listIterator();
		});
	}

	/**
	 * Test the {@code listIterator(int index)} method
	 */
	@Test
	void testListIteratorInt() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.listIterator(0);
		});
	}

	/**
	 * Test the {@code subList(int fromIndex, int toIndex)} method
	 */
	@Test
	void testSubList() {
		// Unimplemented method. Assert that it throws UnsupportedOperationException
		assertThrows(UnsupportedOperationException.class, () -> {
			LinkedList<Integer> list = new LinkedList<>();
			list.subList(0, 1);
		});
	}

}
