package okonkwo;

import java.util.ArrayList;
import java.util.NoSuchElementException;

/**
 * An implementation of a binary search tree using nodes. Nodes in a tree must
 * be of unique values, otherwise {@code DuplicateNodeException} will be thrown.
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * 
 * @param <B> The type of values in the tree; must implement {@code Comparable}
 * 
 * @author Taj Okonkwo
 * @version 1.0
 */
public class BSTree<B extends Comparable<B>> {

	// Data Members
	private Node<B> root;
	private int size;

	// Subclasses
	/**
	 * A node of the tree containing a value, a parent node, and left and right
	 * children
	 * 
	 * @param <B>
	 */
	private static class Node<B extends Comparable<B>> {

		// Node - Data Members
		private B value;
		private Node<B> parent;
		private Node<B> left;
		private Node<B> right;

		// Node - Constructors
		// Default
		public Node() {
			new Node<B>(null);
		}

		// Explicit
		public Node(B value) {
			super();
			this.value = value;
		}

		// Node - Getters and Setters
		public B getValue() {
			return value;
		}

		public void setValue(B value) {
			this.value = value;
		}

		public Node<B> getParent() {
			return parent;
		}

		public void setParent(Node<B> parent) {
			this.parent = parent;
		}

		public Node<B> getLeft() {
			return left;
		}

		public void setLeft(Node<B> left) {
			this.left = left;
		}

		public Node<B> getRight() {
			return right;
		}

		public void setRight(Node<B> right) {
			this.right = right;
		}

	}

	// Class Exceptions
	/**
	 * Thrown when a tree needs to access an element, but the tree is empty
	 */
	private static class EmptyTreeException extends RuntimeException {

		public EmptyTreeException() {
			new EmptyTreeException("");
		}

		public EmptyTreeException(String msg) {
			super(msg);
		}

	}

	/**
	 * Thrown when trying to add a node of equal value to a pre-existing node
	 */
	private static class DuplicateNodeException extends RuntimeException {

		public DuplicateNodeException() {
			new DuplicateNodeException("");
		}

		public DuplicateNodeException(String msg) {
			super(msg);
		}

	}

	// Constructors
	/**
	 * Default Constructor | Create empty tree
	 */
	public BSTree() {
		root = null;
	}

	// New Methods
	// Public
	/**
	 * Add a node to the tree
	 * 
	 * @param value - the value of the added node
	 */
	public void add(B value) {
		// Call <add()> for an instantiated Node of value <value>
		add(new Node<B>(value), true);
	}

	/**
	 * Remove a value from the tree
	 * 
	 * @param value - the value to remove
	 * @throws EmptyTreeException     if attempting to remove an element from an
	 *                                empty tree
	 * @throws NoSuchElementException if {@code value} does not exist in the tree
	 */
	public void remove(B value) {
		// 1. Search for the node to remove <toRemove> with value <value>
		Node<B> toRemove = search(value);

		// 2. Disconnect children and parent. If no parent exists, you have the root
		// node. Ignore the step of disconnecting the parent but set the stored root to
		// null.
		Node<B> parent = toRemove.getParent();
		Node<B> left = toRemove.getLeft();
		Node<B> right = toRemove.getRight();

		// Disconnect children
		if (left != null)
			left.setParent(null);
		if (right != null)
			right.setParent(null);

		toRemove.setLeft(null);
		toRemove.setRight(null);

		// Disconnect parent
		if (parent != null) {
			if (toRemove == parent.getLeft()) // Using '==' works because we are comparing instances, not values
				parent.setLeft(null);
			else if (toRemove == parent.getRight())
				parent.setRight(null);
			toRemove.setParent(null);
		} else
			clear();

		// 3. Add the left and right children of <toRemove> back to the tree
		add(left, false);
		add(right, false);

		// 4. Decrement size
		size--;
	}

	// Private
	/**
	 * Add a node to the tree
	 * 
	 * @param node       - the node to be added
	 * @param changeSize - Should {@code size} change after the addition?
	 * @throws DuplicateNodeException if a node of identical value already exists in
	 *                                the tree
	 */
	private void add(Node<B> node, boolean changeSize) {
		// 1. Check for the root. If there's no root, set it to <node> and increment
		// size.

		// 2. If there is a root, keep track of it as <parent>.
		Node<B> parent;
		if (isEmpty()) {
			root = node;
			if (changeSize)
				size++;
			return;
		} else {
			parent = root;
		}

		// 3. Compare <parent> value to that of <node>.
		// 3a. If <node> value is smaller, make <parent.left> new <parent> if not null.

		// 3b. If values are equal, throw DuplicateNodeException

		// 3c. If it's greater, make <parent.right> the new <parent> if not null.

		// 4. If <parent.left> or <parent.right> is null, set those values to <node>.
		// Make sure to set new parent.
		while (true) {
			if (node.getValue().compareTo(parent.getValue()) < 0) {
				// Search left
				if (parent.getLeft() != null)
					parent = parent.getLeft();
				else {
					node.setParent(parent);
					parent.setLeft(node);
					break;
				}
			} else if (node.getValue().compareTo(parent.getValue()) == 0)
				throw new DuplicateNodeException("A value [" + node.getValue() + "] node already exists in the tree.");
			else {
				// Search right
				if (parent.getRight() != null)
					parent = parent.getRight();
				else {
					node.setParent(parent);
					parent.setRight(node);
					break;
				}
			}
		}

		// 5. Increment <size>.
		if (changeSize)
			size++;
	}

	/**
	 * Go down tree until a node of {@code value} is found, then return the node if
	 * there is one
	 * 
	 * @param value - the value of the node to be found
	 * @return the node of the same value as {@code value}
	 * @throws EmptyTreeException     if searching on an empty tree
	 * @throws NoSuchElementException if a node of same value as {@code value} does
	 *                                not exist
	 */
	private Node<B> search(B value) {
		// 1. Keep track of the root. Set it to the variable <parent>. If root is null,
		// throw EmptyTreeException
		if (isEmpty())
			throw new EmptyTreeException("The tree is empty, so no value can be searched for.");
		Node<B> parent = root;

		// 2. Compare <parent> value to <value>.
		// 2a. If <value> is smaller, make <parent.left> the new <parent> if not null.

		// 2b. If values are equal, return <parent>

		// 2c. If <value> is greater, make <parent.right> the new <parent> if not null.

		// 3. If <parent.left> or <parent.right> is null, throw NoSuchElementException.
		while (true) {
			if (value.compareTo(parent.getValue()) < 0) {
				// Search left
				if (parent.getLeft() != null)
					parent = parent.getLeft();
				else
					throw new NoSuchElementException("A value [" + value + "] node could not be found.");
			} else if (value.compareTo(parent.getValue()) == 0)
				return parent;
			else {
				// Search right
				if (parent.getRight() != null)
					parent = parent.getRight();
				else
					throw new NoSuchElementException("A value [" + value + "] node could not be found.");
			}
		}
	}

	// List Methods
	// Public
	/**
	 * Convert the tree into an {@code ArrayList} of ascending values
	 * 
	 * @return the {@code ArrayList} representation of the tree
	 */
	public ArrayList<B> toList() {
		// Return <subTreeList> for the root. If <root> is null, return an empty list
		if (root != null)
			return (ArrayList<B>) subTreeList(root);
		return new ArrayList<B>();
	}

	/**
	 * Return the size of the tree
	 * 
	 * @return how many values are in the tree
	 */
	public int size() {
		return size;
	}

	/**
	 * Remove all values from the tree (Set the root node to {@code null})
	 */
	public void clear() {
		root = null;
	}

	/**
	 * Is the tree empty? (Is there a root node)
	 * 
	 * @return whether there are zero elements in the tree
	 */
	public boolean isEmpty() {
		return (root == null);
	}

	/**
	 * Returns whether a value exists in the tree by searching through it
	 * 
	 * @param value - the value to search for
	 * @return if the element exists
	 */
	public boolean contains(B value) {
		try {
			return (search(value) != null);
		} catch (EmptyTreeException emptyTree) {
			return false;
		} catch (NoSuchElementException noElement) {
			return false;
		}
	}

	// Private
	/**
	 * Generate an {@code ArrayList} of all descendant nodes starting at
	 * {@code node}
	 * 
	 * @param <B>  - the type of node values
	 * @param node - the node from which to build the list
	 * @return the {@code ArrayList} representation of the sub-nodes
	 */
	private static <B> ArrayList<? extends B> subTreeList(Node<? extends B> node) {
		// 1. Create a <returnList>
		ArrayList<B> returnList = new ArrayList<>();

		// 2. If <node>'s left child isn't null, add all of <subTreeList> nodes from
		// left child to <returnList>
		if (node.getLeft() != null)
			returnList.addAll(subTreeList(node.getLeft()));

		// 3. Add <node.value> to the return list
		returnList.add(node.getValue());

		// 4. If <node>'s right child isn't null, add all of <subTreeList> nodes from
		// right child to <returnList>
		if (node.getRight() != null)
			returnList.addAll(subTreeList(node.getRight()));

		// 5. Return <returnList>
		return returnList;
	}

	// Object Methods
	/**
	 * Returns the tree as a string
	 * 
	 * @return the string representation of the tree
	 */
	@Override
	public String toString() {
		return toList().toString();
	}
}
