package tester;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Test;

import okonkwo.BSTree;

/**
 * A JUnit tester class for the {@code BSTree} class. Tests all methods of the class.
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * 
 * @author Taj Okonkwo
 * @version 1.0
 */
class TestBSTree {

	/**
	 * Test the default constructor
	 */
	@Test
	void testBSTreeDefault() {
		// 1. Create a new BSTree of type Integer
		BSTree<Integer> tree = new BSTree<>();
		
		// 2. Assert that it is empty
		assertTrue(tree.isEmpty());
	}
	
	/**
	 * Test the explicit constructor
	 */
	void testBSTreeExplicit() {
		// 1. Create a list of integers
		ArrayList<Integer> list = new ArrayList<>();
		for (int i = 0; i < 100; i++)
			list.add((int) (Math.random() * 100));
		
		// 2. Create a new BSTree of type Integer with the list
		BSTree<Integer> tree = new BSTree<Integer>(list);
		
		// 3. Assert that the tree contains all the values in the list
		for (Integer i: list)
			assertTrue(tree.contains(i));
	}

	/**
	 * Test the {@code add()} method
	 */
	@Test
	void testAdd() {
		// 1. Create a new BSTree of type Double
		BSTree<Double> tree = new BSTree<>();
		
		// 2. Populate the tree with random values. Assert that each value is contained (randomTree() method but with assertions)
		for (int i = 0; i < 100; i++) {
			double value = Math.random();
			tree.add(value);
			assertTrue(tree.contains(value));
		}
		
		// 3. Try to add an element of the same value and check that the addition will be prevented
		ArrayList<Double> treeList = tree.toList();
		double myElement = treeList.get((int) (Math.random() * treeList.size()));
		assertThrows(BSTree.DuplicateNodeException.class, () -> {
			tree.add(myElement);
		});
	}

	/**
	 * Test the {@code remove()} method
	 */
	@Test
	void testRemove() {
		// 1. Create a new BSTree of type Double populated with random values
		BSTree<Double> tree = randomTree();
		
		// 2. Remove a random value and assert that it no longer exists.
		ArrayList<Double> treeList = tree.toList();
		double myElement = treeList.get((int) (Math.random() * treeList.size()));
		tree.remove(myElement);
		assertTrue(!tree.contains(myElement));
		
		// 3. Try to remove a value that doesn't exist and assert that the value cannot be removed.
		assertThrows(NoSuchElementException.class, () -> {
			tree.remove(1.5);
		});
		
		// 4. Try to remove from an empty tree and assert that values can't be removed
		assertThrows(BSTree.EmptyTreeException.class, () -> {
			(new BSTree<Double>()).remove(0.0);
		});
		
		// 5. Remove all elements from tree and assert that removal throws the EmptyTreeException
		for (Double d: tree.toList())
			tree.remove(d);
		assertThrows(BSTree.EmptyTreeException.class, () -> {
			tree.remove(0.0);
		});
	}

	/**
	 * Test the {@code toList()} method
	 */
	@Test
	void testToList() {
		// 1. Create a randomTree()
		BSTree<Double> tree = randomTree();
		
		// 2. Turn the tree into a list
		ArrayList<Double> treeList = tree.toList();
		
		// 3. Assert that the items are sorted and that each one can be found in the tree
		for (int i = 0; i < treeList.size() - 1; i++) {
			assertTrue(tree.contains(treeList.get(i)));
			assertTrue(treeList.get(i) <= treeList.get(i + 1));
		}
	}

	/**
	 * Test the {@code size()} method
	 */
	@Test
	void testSize() {
		// 1. Create a randomTree()
		BSTree<Double> tree = randomTree();
		
		// 2. Turn the tree into a list
		ArrayList<Double> treeList = tree.toList();
		
		// 3. Assert that the size is the same as the tree's size
		assertTrue(treeList.size() == tree.size());
	}

	/**
	 * Test the {@code clear()} method
	 */
	@Test
	void testClear() {
		// 1. Create a randomTree()
		BSTree<Double> tree = randomTree();
		
		// 2. Clear its elements
		tree.clear();
		
		// 3. Assert that a search will throw EmptyTreeException
		assertThrows(BSTree.EmptyTreeException.class, () -> {
			tree.remove(0.0);
		});
	}

	/**
	 * Test the {@code clear()} method
	 */
	@Test
	void testIsEmpty() {
		// 1. Create a randomTree()
		BSTree<Double> tree = randomTree();
		
		// 2. Clear its elements
		tree.clear();
		
		// 3. Assert that the tree is empty
		assertTrue(tree.isEmpty());
	}

	/**
	 * Test the {@code contains()} method
	 */
	@Test
	void testContains() {
		// 1. Create an empty tree
		BSTree<Double> tree = new BSTree<>();
		
		// 2. Add a value
		double value = 0.123;
		tree.add(value);
		
		// 3. Assert that the value is contained
		assertTrue(tree.contains(value));
		
		// 4. Remove the value and assert that the value is not contained
		tree.remove(value);
		assertTrue(!tree.contains(value));
		
		// 5. Assert that searching for a value that the tree has never contained will return false
		assertTrue(!tree.contains(-1.0));
	}

	/**
	 * Test the {@code toString()} method
	 */
	@Test
	void testToString() {
		// 1. Create a randomTree()
		BSTree<Double> tree = randomTree();
		
		// 2. Convert to string
		String treeString = tree.toString();
		
		// 3. Assert that the string contains every value
		String[] splitString = treeString.substring(1, treeString.length() - 1).split(", ");
		for (String s: splitString) {
			double parse = Double.parseDouble(s);
			assertTrue(tree.contains(parse));
		}
	}
	
	/**
	 * Generate a tree of 100 random double values
	 * @return the tree
	 */
	private static BSTree<Double> randomTree() {
		// 1. Create a new BSTree of type Double
		BSTree<Double> tree = new BSTree<>();
		
		// 2. Populate the tree with random values.
		for (int i = 0; i < 100; i++) {
			double value = Math.random();
			tree.add(value);
		}
		
		// 3. Return the tree
		return tree;
	}

}
