package tester;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

import okonkwo.Dictionary;

/**
 * A JUnit tester class for the {@code Dictionary} class. Tests all methods of the class.
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * 
 * @author Taj Okonkwo
 * @version 1.0
 */
class TestDictionary {

	/**
	 * Test the constructor
	 */
	@Test
	void testDictionary() {
		// 1. Create a new Dictionary
		Dictionary dict = new Dictionary();
		
		// 2. Assert that it is empty
		assertTrue(dict.isEmpty());
	}

	/**
	 * Test the {@code add()} method (Overrode by {@code insertWordNode()})
	 */
	@Test
	void testAddString() {
		// 1. Create a new Dictionary
		Dictionary dict = new Dictionary();
		
		// 2. Assert that an addition from the superclass will throw an exception
		assertThrows(UnsupportedOperationException.class, () -> {
			dict.add("my word");
		});
	}

	/**
	 * Test the {@code contains()} method (Overrode by {@code spellCheck()})
	 */
	@Test
	void testContains() {
		// 1. Create a new Dictionary
		Dictionary dict = new Dictionary();
		
		// 2. Assert that a contains from the superclass will throw an exception
		assertThrows(UnsupportedOperationException.class, () -> {
			dict.contains("my word");
		});
	}

	/**
	 * Test the {@code remove()} method (Overrode by {@code checkWord()})
	 */
	@Test
	void testRemoveString() {
		// 1. Create a new Dictionary
		Dictionary dict = new Dictionary();
		
		// 2. Assert that a removal from the superclass will throw an exception
		assertThrows(UnsupportedOperationException.class, () -> {
			dict.remove("to remove");
		});
	}

	/**
	 * Test the {@code insertWordNode()} method
	 */
	@Test
	void testInsertWordNode() {
		// 1. Create a new Dictionary
		Dictionary dict = new Dictionary();
		
		// 2. Populate it with strings
		for (int i = 0; i < 100; i++) {
			dict.insertWordNode(randomAlphaString(10));
		}
		
		// 3. Assert that a word with non-letter characters or an empty word will throw an exception
		assertThrows(IllegalArgumentException.class, () -> {
			dict.insertWordNode("my word");
		});
		assertThrows(IllegalArgumentException.class, () -> {
			dict.insertWordNode("myword123");
		});
		assertThrows(IllegalArgumentException.class, () -> {
			dict.insertWordNode("");
		});
	}

	/**
	 * Test the {@code checkWord()} method
	 */
	@Test
	void testCheckWord() {
		// 1. Create a new Dictionary
		Dictionary dict = new Dictionary();
		
		// 2. Populate it with strings
		for (int i = 0; i < 100; i++) {
			dict.insertWordNode(randomAlphaString(10));
		}
		
		// 3. Pick a random word from the dictionary and check if it can be removed
		String randomWord = dict.toList().get((int) (Math.random() * dict.size()));
		dict.checkWord(randomWord);
	}
	
	/**
	 * Test the {@code spellCheck()} method
	 */
	@Test
	void testSpellCheck() {
		// 1. Create a new Dictionary
		Dictionary dict = new Dictionary();
		
		// 2. Populate it with strings
		for (int i = 0; i < 100; i++) {
			dict.insertWordNode(randomAlphaString(10));
		}
		
		// 3. Pick a random word from the dictionary and check if it exists
		String randomWord = dict.toList().get((int) (Math.random() * dict.size()));
		assertTrue(dict.spellCheck(randomWord));
		
		// 4. Check a word that doesn't exist
		assertFalse(dict.spellCheck("thisworddoesnotexist"));
		
		// 5. Check the random word in uppercase to ensure case insensitivity
		assertTrue(dict.spellCheck(randomWord.toUpperCase()));
	}
	
	/**
	 * Generate a random string of letters
	 * @param length - the length of the string
	 * @return a random string of letters
	 */
	private static String randomAlphaString(int length) {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < length; i++) {
			char c = (char) ('a' + Math.random() * 26);
			sb.append(c);
		}
		return sb.toString();
	}

}
