package tester;

import okonkwo.*;
import java.util.ArrayList;

/**
 * Test the {@code SalesSlip} class
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 */
public class TestSalesSlip {
	
	/**
	 * Main method for testing
	 * @param args
	 */
	public static void main(String[] args) {
		// 1. Create slip
		SalesSlip slip = new SalesSlip();
		
		// 2. Populate it with items
		for (int i = 1; i <= 20; i++) {
			slip.addItem(new SalesItem("Item " + i, (float) Math.random() * 100, (int) ((float) Math.random() * 100)));
		}
		
		// 3. Display all items
		System.out.println("Items");
		System.out.println(slip);
		
		// 4. Display total costs
		System.out.println("Total costs");
		System.out.println(slip.totalSales());
	}

}
