package tester;

import okonkwo.*;
import java.util.ArrayList;

/**
 * Test the {@code SalesItem} class
 * <p>Comments, documentation, and parts of code generated by GitHub Copilot</p>
 * @author Taj Okonkwo
 * @version 1.0
 */
public class TestSalesItem {

	/**
	 * Main method for testing
	 * @param args
	 */
	public static void main(String[] args) {
		// TEST 1: SalesItem instances
		System.out.println("TEST 1: SalesItem instances");
		// 1. Create many salesItems
		ArrayList<SalesItem> items = new ArrayList<>();
		items.add(new SalesItem("Apples", 1.58f, 1));
		items.add(new SalesItem("Bananas", 2.50f, 3));
		items.add(new SalesItem("Salad", 5.00f, 100));
		
		// 2. Print all items
		for (SalesItem i: items)
			System.out.println(i);
	}
	
}
